new Vue({
  el: '#form',
  data: {
    seriesTitre : '',
    numero : '0',
    albumTitre  : '',
    editionOriginale  : false,
    categorie : '',
    idDessinateur : '',
    idScenariste : '',
    idColoriste : '',
    prixVente : '0',
    editeur : '',
    editionOriginale : '',
    image : '',
    descriptif : '',
    reference	 : '',
    depotLegal : '',
    dateSortie : '',
    dateImpression : '',
    commentaire  : '',
    image2 : '',
    image3 : '',
    image4 : '',
    nbPages : '0',
    matiere : '',
    aspect : '',
    certificat : '',
    numerote : '',
    signe : '',
    packaging : '',
    horsCommerce : '',
    hauteur : '0',
    largeur : '0',
    profondeur : '0',
    cote : '0',
    cotePerso : '0',
    dateModifCote : '',
    origineCote : ''
  }
})
